#------------------------------------------------------------------------------------
#--------------------------build-----------------------------------------------------
#------------------------------------------------------------------------------------
FROM ubuntu:xenial as build

RUN apt-get update && \
    apt-get install -y aptitude gcc g++ make patch unzip python build-essential \
    autoconf automake libtool pkg-config libxml2-dev zlib1g-dev openssl libssl-dev\
    liblzma-dev libzip-dev libbz2-dev git cmake extra-cmake-modules

# Libs path for ffmpeg(depends on serval libs).
ENV PKG_CONFIG_PATH /usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig


# Build srt
RUN cd /tmp && git clone https://github.com/Haivision/srt.git && cd srt \ 
&& cmake . -DENABLE_LOGGING=1 -DENABLE_PROFILE=1 -DENABLE_STATIC=1  -DUSE_STATIC_LIBSTDCXX=1 -DENABLE_THREAD_CHECK=0 \
&& make && make install

# Build Tsduck
RUN cd /tmp && git clone https://github.com/tsduck/tsduck.git && cd tsduck && ./build/install-prerequisites.sh \
&&  make NOPCSC=1 NOCURL=1 NODTAPI=1 NOSRT=0 NOTEST=1 \
&&  make install 
